### ISSUE TITLE
Does not work with Hoppers on latest Mineclone2 

### ISSUE THREAD

**Issue by JamesClarke7283** [ketwaroo/minetest-k-recycler#1]
The items don't go into the Recyclebin from the hopper in mineclone2 because they changed the implementation for hoppers.

Here is the related issue:
https://git.minetest.land/MineClone2/MineClone2/pulls/3980

**Comment by ketwaroo** [comment]
So technically, mineclone2 isn't supported. the mod supports [mineclonia ](https://content.minetest.net/packages/ryvnf/mineclonia/)

Their new hopper API looks interesting though. It's similar to mineclonia's. I don't have mineclone2 installed locally at the moment though. Not making any promises but I can try looking into implementing it at some point.

The problems that could arise is that mineclonia has diverged a bit from mineclone2 and it may be incompatible on some other level.

**Comment by ketwaroo** [comment]
@JamesClarke7283  I added a branch to somewhat support mineclone2 hoppers

I've only tested it superficially and would appreciate feedback if you have any.
